openapi: "3.0.3"
info:
  title: Expense Tracker API Endpoints
  version: "1.0"
servers:
  - url: http://localhost:3000/api/v1
    description: Localhost

paths:
  /auth/signup:
    post:
      description: Sign up user
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                email:
                  type: string
                password:
                  type: string
                profile:
                  type: image/*
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      fullName:
                        type: string
                      email:
                        type: string
                      profile:
                        type: string
                      _id:
                        type: string
                      createdAt:
                        type: string
                  token:
                    type: string

  /auth/signin:
    post:
      description: Sign in user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      fullName:
                        type: string
                      email:
                        type: string
                      profile:
                        type: string
                      _id:
                        type: string
                      createdAt:
                        type: string
                  token:
                    type: string

  /users/:
    get:
      description: Get All Users

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    fullName:
                      type: string
                    email:
                      type: string
                    profile:
                      type: string
                    _id:
                      type: string
                    createdAt:
                      type: string

  /users/{id}:
    get:
      description: Get Specific Users

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  fullName:
                    type: string
                  email:
                    type: string
                  profile:
                    type: string
                  _id:
                    type: string
                  createdAt:
                    type: string

    put:
      description: Update Specific Users

      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                email:
                  type: string
                password:
                  type: string
                profile:
                  type: image/*
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      fullName:
                        type: string
                      email:
                        type: string
                      profile:
                        type: string
                      _id:
                        type: string
                      createdAt:
                        type: string

    delete:
      description: Delete Specific Users
      responses:
        "200":
          description: User deleted successfully
